### ISSUE TITLE
do you have some roadmap on this project

### ISSUE THREAD

**Issue by chenyq2** [choppsv1/netconf#18]
hi Christian, 
first thank you for your contributing on this interesting netconf project. I search some netconf  frame code and find out your code.
I have a question, do you have some roadmap or some plan to support those unimplemented functions.
thanks.

**Comment by choppsv1** [comment]
Hi chenyuqiang,

We are using this internally at DT for various projects that require
simple netconf server support (e.g., see the jdsu-ocm project also on
github).  We don't have a roadmap as such, but rather I've been adding
to the project as we've needed more functionality. That said, I believe
that in the next few months I'll be using the config functions, I'm not
sure how much extra fancy features I'd be adding for them though.

When I posted this I was hoping that others might add better support for
filtering, but that hasn't happened yet. :)

Thanks,
Chris.

**Comment by chenyq2** [comment]
Hi Christian,

thanks your kind answer.
basically I think your this project is a good python based netconf frame code. I will study your code.
