### ISSUE TITLE
Support for NETCONF Call Home?

### ISSUE THREAD

**Issue by hschulzbln** [choppsv1/netconf#24]
Hi Chris,

Does your package support NETCONF call home? If not, do you plan to support it?

  "NETCONF Call Home and RESTCONF Call Home"
  https://tools.ietf.org/html/rfc8071.html

Thanks,
Holger

**Comment by choppsv1** [comment]
It doesn't have direct support for this currently. I don't think it's that hard to add though.

Are you interested in the server side, the client side or both? Obviously both is best (maybe required to be able to test :) I'm just curious if one is more important to you than the other.

**Comment by hschulzbln** [comment]
Thanks for the fast response. I was interested in the client side but yes, having it in client and server makes more sense. I found your package being used in CORD's VOLTHA. But today I noticed that only parts of the code are used (?) and in addition other packages (ncclient) are used as well which should already support call home. So, I do not have the need anymore for call home in your package. Sorry!

**Comment by choppsv1** [comment]
I actually added the basic support to sshutil (which netconf uses) with a test. I wonder if they used ncclient for the extra API it provided? I recently started to add some more friendly API (get, get_config with filtering) to the client code as well as improved the documentation.
