### ISSUE TITLE
Server-side class auto-generate

### ISSUE THREAD

**Issue by amorxj** [choppsv1/netconf#25]
Hi @choppsv1 ,

I just read this fantastic project ,
and I want to find out if there is a way to get pthon class  from yang file .

Thansks

**Comment by choppsv1** [comment]
We don't have this functionality no. It would be a nice add though. Get's are pretty easy to handle anyway, but the config side isn't as straight-forward so something that did a lot of that work would be nice.

If you need to handle a lot of config or complex usage you might take a look at sysrepo.

**Comment by amorxj** [comment]
Thanks for your reply @choppsv1 

You are right, sysrepo seems more complex and fits for complex scene.
I will take a look at sysrepo.

This project is a good start for me，thank you @choppsv1
