### ISSUE TITLE
question about project status

### ISSUE THREAD

**Issue by tommyjcarpenter** [choppsv1/netconf#29]
Hello,

I was going to email this, but I can't find your email on any medium.. your linkedIn doesn't show it,  your github profile doesn't show it, and even your linked blog has no contact information that I can find... So this is the only way I know how to contact you! I'd be happy to discuss over email instead. 

Is this project robust to implement a NETCONF server in Python? Is this complete w.r.t. RFC 6241? Is it under active development? I'm debating using it for a project and am wondering as to the maturity of this project. It's one of the only NETCONF server implementations I've found, in any language actually.

**Comment by tommyjcarpenter** [comment]
Looking into this code further, I believe one of the main functions we will need is `rpc_edit_config`. I know this is currently not implemented, but do you have an idea of what this function API should look like if we were to try to implement this ourselves?

**Comment by choppsv1** [comment]
So, most of the functionality of edit config is is in the back-end where you store your config data. This code doesn't supply that back-end DB. Implementing the edit-config RPC is easy to do (just parse the RPC parameters and pass them to the back-end basically). I'm a little surprised that I never put that basic code there, as I did add it for the client code.

To answer your earlier questions:

The protocol implementation is RFC6241 compliant. The code is pretty mature, but I certainly can't promise it's bug free.

The last addition I made to the code is very useful and that is transparently supporting XPATH filtering. The non-xpath (i.e., xml node filters) filtering support is pretty tricky as it was designed to try and allow a more optimal inline filter/state fetch vs. the "fetch all and prune" that the xpath filtering performs. That said the "fetch all and prune" method works really well and is simple if it doesn't present performance/scaling issues. Even then it's probably not hard to add simple top of path processing if that is where the expense is in fetching config/state from the back-end.

One feature I've wanted to add is to provide conversion from any xml node filter into an xpath filter. This would allow node filters to be transparently handled like xpath are in the "fetch all and prune" mode. I think this would round out the feature set and provide a simple, yet full plug and play a NETCONF server (i.e., not require much extra code).

Nothing is free obviously, some work will need to be done to make this work for you in your project; however, you won't need to do any of the NETCONF protocol work, that's all there. And I'd certainly welcome any general improvements if you do choose to use this code and code up some useful general functions.

**Comment by choppsv1** [comment]
I'm surprised that github doesn't have an email option. In any case google should have turned up my IETF profile which does include an email that I don't actually want to put here. :)

**Comment by tommyjcarpenter** [comment]
Thanks for the reply! 

Someone that I work with who is much more familiar with this space than myself suggested that the locking mechanism can get hairy. Specifically they raised concurrent access to configuration data (locking parts of the data tree and release it), and processing to get confirmation if the devices supports a certain configuration based on the existing hardware and configuration. 

I will email you privately.
