### ISSUE TITLE
Add support for test-option

### ISSUE THREAD

**Issue by flazzarini** [choppsv1/netconf#30]
Currenlty there is no support for `test-option` for the netconf `edit-config` operation. This ticket should serve as a feature request.

https://tools.ietf.org/html/rfc6241#section-7.2

**Comment by choppsv1** [comment]
I assume this is for the client code. Not sure how I missed this (and the error-option). It makes the most sense to me add these parameters before the config in the API but that would break the API compat then. So I guess we'll need to add them after the config / timeout parameters.
