### ISSUE TITLE
MissingElementProtoError in rpc_edit_config

### ISSUE THREAD

**Issue by vaibhgupta157** [choppsv1/netconf#32]
I am trying to implement edit-config rpc in netconf server. Definition of my func in NetconfMethod class is something like 
this.
```
def rpc_edit_config(self, session, rpc, target_elm, config):
```
Everything works fine except for the MissingElementProtoError error. In request from client if any of the parameter 'target_elm' or 'config' is missing it generates "Unexpected token; characters were not expected but got rpc_edit_config() takes exactly 5 arguments ". I want to generate "MissingElementProtoError" in case of any of the element missing as it does in case of rpc_get_config method. I don't see any specific code for this in NetconfMethod class.

Note: I am extending class SystemServer in netconf/example/system-server.py for edit-config and other RPCs

**Comment by choppsv1** [comment]
To get he failure you'd like you can just raise the MissingElementProtoError inside your version of rpc_edit_config e.g.,

```
raise netconf.error.MissingElementProtoError(rpc, netconf.util.qname("nc:target"))
```
