### ISSUE TITLE
sshutil.cache:Got unexpected socket error connecting to: localhost:830

### ISSUE THREAD

**Issue by LORDlude** [choppsv1/netconf#33]
i am a new to use netconf,after installing netconf,when i use netconf-client ,the result is:
ERROR:sshutil.cache:Got unexpected socket error connecting to: localhost:830: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/local/bin/netconf-client", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/netconf/__main__.py", line 103, in main
    args.host, args.port, args.username, args.password, debug=args.debug)
  File "/usr/local/lib/python2.7/dist-packages/netconf/client.py", line 481, in __init__
    host, port, "netconf", username, password, debug, cache=cache, proxycmd=proxycmd)
  File "/usr/local/lib/python2.7/dist-packages/sshutil/conn.py", line 158, in __init__
    proxycmd)
  File "/usr/local/lib/python2.7/dist-packages/sshutil/conn.py", line 75, in __init__
    self.ssh = cache.get_ssh_socket(host, port, username, password, debug, proxycmd)
  File "/usr/local/lib/python2.7/dist-packages/sshutil/cache.py", line 334, in get_ssh_socket
    True, debug, proxycmd)
  File "/usr/local/lib/python2.7/dist-packages/sshutil/cache.py", line 137, in _open_ssh_socket
    ossock = cls.open_os_socket(host, port, use_config, debug, proxy)
  File "/usr/local/lib/python2.7/dist-packages/sshutil/cache.py", line 128, in open_os_socket
    raise error  # pylint: disable=E0702
socket.error: [Errno 111] Connection refused

**Comment by choppsv1** [comment]
Looks like something is wrong with your ssh connection to the server. Is your server listening on localhost:830?

**Comment by LORDlude** [comment]
Oh,thank you for your answer, I foeget add the poort 830 to /etc/ssh/ssh_config,.But when I do it, it broken an exception, I found it's because of the Python version. I am using python 2.7.12,,can you give me some advice? THank you, I think my poor english is not a joke fou you 0.0.
The result is:
root@shaolude-virtual-machine:/etc/ssh# netconf-client --hello
Traceback (most recent call last):
  File "/usr/local/bin/netconf-client", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/netconf/__main__.py", line 103, in main
    args.host, args.port, args.username, args.password, debug=args.debug)
  File "/usr/local/lib/python2.7/dist-packages/netconf/client.py", line 481, in __init__
    host, port, "netconf", username, password, debug, cache=cache, proxycmd=proxycmd)
  File "/usr/local/lib/python2.7/dist-packages/sshutil/conn.py", line 158, in __init__
    proxycmd)
  File "/usr/local/lib/python2.7/dist-packages/sshutil/conn.py", line 75, in __init__
    self.ssh = cache.get_ssh_socket(host, port, username, password, debug, proxycmd)
  File "/usr/local/lib/python2.7/dist-packages/sshutil/cache.py", line 334, in get_ssh_socket
    True, debug, proxycmd)
  File "/usr/local/lib/python2.7/dist-packages/sshutil/cache.py", line 209, in _open_ssh_socket
    raise autherr
TypeError: exceptions must be old-style classes or derived from BaseException, not unicode

**Comment by LORDlude** [comment]
> Looks like something is wrong with your ssh connection to the server. Is your server listening on localhost:830?
> […](#)
> On Jan 2, 2020, at 4:40 AM, LORDlude ***@***.***> wrote: i am a new to use netconf,after installing netconf,when i use netconf-client ,the result is: ERROR:sshutil.cache:Got unexpected socket error connecting to: localhost:830: [Errno 111] Connection refused Traceback (most recent call last): File "/usr/local/bin/netconf-client", line 8, in sys.exit(main()) File "/usr/local/lib/python2.7/dist-packages/netconf/main.py", line 103, in main args.host, args.port, args.username, args.password, debug=args.debug) File "/usr/local/lib/python2.7/dist-packages/netconf/client.py", line 481, in init host, port, "netconf", username, password, debug, cache=cache, proxycmd=proxycmd) File "/usr/local/lib/python2.7/dist-packages/sshutil/conn.py", line 158, in init proxycmd) File "/usr/local/lib/python2.7/dist-packages/sshutil/conn.py", line 75, in init self.ssh = cache.get_ssh_socket(host, port, username, password, debug, proxycmd) File "/usr/local/lib/python2.7/dist-packages/sshutil/cache.py", line 334, in get_ssh_socket True, debug, proxycmd) File "/usr/local/lib/python2.7/dist-packages/sshutil/cache.py", line 137, in _open_ssh_socket ossock = cls.open_os_socket(host, port, use_config, debug, proxy) File "/usr/local/lib/python2.7/dist-packages/sshutil/cache.py", line 128, in open_os_socket raise error # pylint: disable=E0702 socket.error: [Errno 111] Connection refused — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I switch the python version of Ubuntu14.04 from2.7.12 to 3.4.3，it still cases an exception，I think maybe it's a bug？
root@shaolude-virtual-machine:~# netconf-client 
Traceback (most recent call last):
  File "/usr/local/bin/netconf-client", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/netconf/__main__.py", line 103, in main
    args.host, args.port, args.username, args.password, debug=args.debug)
  File "/usr/local/lib/python3.4/dist-packages/netconf/client.py", line 481, in __init__
    host, port, "netconf", username, password, debug, cache=cache, proxycmd=proxycmd)
  File "/usr/local/lib/python3.4/dist-packages/sshutil/conn.py", line 158, in __init__
    proxycmd)
  File "/usr/local/lib/python3.4/dist-packages/sshutil/conn.py", line 75, in __init__
    self.ssh = cache.get_ssh_socket(host, port, username, password, debug, proxycmd)
  File "/usr/local/lib/python3.4/dist-packages/sshutil/cache.py", line 334, in get_ssh_socket
    True, debug, proxycmd)
  File "/usr/local/lib/python3.4/dist-packages/sshutil/cache.py", line 209, in _open_ssh_socket
    raise autherr
TypeError: exceptions must derive from BaseException

**Comment by choppsv1** [comment]
The TypeError exception is a bug (i'm testing a fix now), but it's not your issue. It's just a problem with reporting authentication failure. Again I think that you may not actually have something listening on the port or you are blocking it.

Try:

  "sudo ss -anlp | grep 830"

Do you see somehting listening? Do you have any iptables or other firewall blocking ports?

Thanks,
Chris.

**Comment by LORDlude** [comment]
> The TypeError exception is a bug (i'm testing a fix now), but it's not your issue. It's just a problem with reporting authentication failure. Again I think that you may not actually have something listening on the port or you are blocking it. Try: "sudo ss -anlp | grep 830" Do you see somehting listening? Do you have any iptables or other firewall blocking ports? Thanks, Chris.
> […](#)
> On Jan 2, 2020, at 9:31 PM, LORDlude ***@***.***> wrote: Looks like something is wrong with your ssh connection to the server. Is your server listening on localhost:830? … On Jan 2, 2020, at 4:40 AM, LORDlude @.***> wrote: i am a new to use netconf,after installing netconf,when i use netconf-client ,the result is: ERROR:sshutil.cache:Got unexpected socket error connecting to: localhost:830: [Errno 111] Connection refused Traceback (most recent call last): File "/usr/local/bin/netconf-client", line 8, in sys.exit(main()) File "/usr/local/lib/python2.7/dist-packages/netconf/main.py", line 103, in main args.host, args.port, args.username, args.password, debug=args.debug) File "/usr/local/lib/python2.7/dist-packages/netconf/client.py", line 481, in init host, port, "netconf", username, password, debug, cache=cache, proxycmd=proxycmd) File "/usr/local/lib/python2.7/dist-packages/sshutil/conn.py", line 158, in init proxycmd) File "/usr/local/lib/python2.7/dist-packages/sshutil/conn.py", line 75, in init self.ssh = cache.get_ssh_socket(host, port, username, password, debug, proxycmd) File "/usr/local/lib/python2.7/dist-packages/sshutil/cache.py", line 334, in get_ssh_socket True, debug, proxycmd) File "/usr/local/lib/python2.7/dist-packages/sshutil/cache.py", line 137, in _open_ssh_socket ossock = cls.open_os_socket(host, port, use_config, debug, proxy) File "/usr/local/lib/python2.7/dist-packages/sshutil/cache.py", line 128, in open_os_socket raise error # pylint: disable=E0702 socket.error: [Errno 111] Connection refused — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. I switch the python version of Ubuntu14.04 from2.7.12 to 3.4.3，it still cases an exception，I think maybe it's a bug？ ***@***.***:~# netconf-client Traceback (most recent call last): File "/usr/local/bin/netconf-client", line 8, in sys.exit(main()) File "/usr/local/lib/python3.4/dist-packages/netconf/main.py", line 103, in main args.host, args.port, args.username, args.password, debug=args.debug) File "/usr/local/lib/python3.4/dist-packages/netconf/client.py", line 481, in init host, port, "netconf", username, password, debug, cache=cache, proxycmd=proxycmd) File "/usr/local/lib/python3.4/dist-packages/sshutil/conn.py", line 158, in init proxycmd) File "/usr/local/lib/python3.4/dist-packages/sshutil/conn.py", line 75, in init self.ssh = cache.get_ssh_socket(host, port, username, password, debug, proxycmd) File "/usr/local/lib/python3.4/dist-packages/sshutil/cache.py", line 334, in get_ssh_socket True, debug, proxycmd) File "/usr/local/lib/python3.4/dist-packages/sshutil/cache.py", line 209, in _open_ssh_socket raise autherr TypeError: exceptions must derive from BaseException — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

I think I have open the listening on port 830 successfuly.I also check the selinux, but I found my os(Ubuntu14.04) doesn't have selinux.
shaolude@shaolude-virtual-machine:~$ sudo ss -anlp | grep 830
tcp    LISTEN     0      128                    *:830                   *:*      users:(("sshd",1138,3))
tcp    LISTEN     0      128                   :::830                  :::*      users:(("sshd",1138,4))

**Comment by choppsv1** [comment]
What netconf server are you running? The ss output indicates sshd is listening on 830. I would expect that to be a netconf server process.

Thanks,
Chris.

**Comment by LORDlude** [comment]
> What netconf server are you running? The ss output indicates sshd is listening on 830. I would expect that to be a netconf server process. Thanks, Chris.
> […](#)
> On Jan 5, 2020, at 9:21 PM, LORDlude ***@***.***> wrote: The TypeError exception is a bug (i'm testing a fix now), but it's not your issue. It's just a problem with reporting authentication failure. Again I think that you may not actually have something listening on the port or you are blocking it. Try: "sudo ss -anlp | grep 830" Do you see somehting listening? Do you have any iptables or other firewall blocking ports? Thanks, Chris. … On Jan 2, 2020, at 9:31 PM, LORDlude @.> wrote: Looks like something is wrong with your ssh connection to the server. Is your server listening on localhost:830? … On Jan 2, 2020, at 4:40 AM, LORDlude @.> wrote: i am a new to use netconf,after installing netconf,when i use netconf-client ,the result is: ERROR:sshutil.cache:Got unexpected socket error connecting to: localhost:830: [Errno 111] Connection refused Traceback (most recent call last): File "/usr/local/bin/netconf-client", line 8, in sys.exit(main()) File "/usr/local/lib/python2.7/dist-packages/netconf/main.py", line 103, in main args.host, args.port, args.username, args.password, debug=args.debug) File "/usr/local/lib/python2.7/dist-packages/netconf/client.py", line 481, in init host, port, "netconf", username, password, debug, cache=cache, proxycmd=proxycmd) File "/usr/local/lib/python2.7/dist-packages/sshutil/conn.py", line 158, in init proxycmd) File "/usr/local/lib/python2.7/dist-packages/sshutil/conn.py", line 75, in init self.ssh = cache.get_ssh_socket(host, port, username, password, debug, proxycmd) File "/usr/local/lib/python2.7/dist-packages/sshutil/cache.py", line 334, in get_ssh_socket True, debug, proxycmd) File "/usr/local/lib/python2.7/dist-packages/sshutil/cache.py", line 137, in _open_ssh_socket ossock = cls.open_os_socket(host, port, use_config, debug, proxy) File "/usr/local/lib/python2.7/dist-packages/sshutil/cache.py", line 128, in open_os_socket raise error # pylint: disable=E0702 socket.error: [Errno 111] Connection refused — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. I switch the python version of Ubuntu14.04 from2.7.12 to 3.4.3，it still cases an exception，I think maybe it's a bug？ @.***:~# netconf-client Traceback (most recent call last): File "/usr/local/bin/netconf-client", line 8, in sys.exit(main()) File "/usr/local/lib/python3.4/dist-packages/netconf/main.py", line 103, in main args.host, args.port, args.username, args.password, debug=args.debug) File "/usr/local/lib/python3.4/dist-packages/netconf/client.py", line 481, in init host, port, "netconf", username, password, debug, cache=cache, proxycmd=proxycmd) File "/usr/local/lib/python3.4/dist-packages/sshutil/conn.py", line 158, in init proxycmd) File "/usr/local/lib/python3.4/dist-packages/sshutil/conn.py", line 75, in init self.ssh = cache.get_ssh_socket(host, port, username, password, debug, proxycmd) File "/usr/local/lib/python3.4/dist-packages/sshutil/cache.py", line 334, in get_ssh_socket True, debug, proxycmd) File "/usr/local/lib/python3.4/dist-packages/sshutil/cache.py", line 209, in _open_ssh_socket raise autherr TypeError: exceptions must derive from BaseException — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. I think I have open the listening on port 830 successfuly.I also check the selinux, but I found my os(Ubuntu14.04) doesn't have selinux. ***@***.***:~$ sudo ss -anlp | grep 830 tcp LISTEN 0 128 :830 : users:(("sshd",1138,3)) tcp LISTEN 0 128 :::830 ::: users:(("sshd",1138,4)) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

I use xshell to connect the VMware. I use the OS itself as netconf server,I start the server netconfd. And I open another window as client to connect the server.I think it should ok.

Thanks.

**Comment by choppsv1** [comment]
I think something is wrong in the connection path. I'm not sure what xshell is though. I don't think sshd listening on port 830 is getting you what you want. Can you run the netconf client inside vmware?

Thanks,
Chris.

**Comment by LORDlude** [comment]
@choppsv1 I have anoter confusion : netconf-client … --hello,what's the meaning of "...", the ip address of netconf server?
thanks

**Comment by LORDlude** [comment]
@choppsv1 OK, I try to run the  netconf-client directly inside vmware.But it causes the same problem(Exception).

**Comment by choppsv1** [comment]
Can you run "ss -anlp" inside the VMware to see that netconfd is listening on port 830? "--hello" does only  a hello exchange with the netconf server and prints the capabilities that the server returned from this exchange. Also try specifying the global IP address of the server (one you can ping from where you are running the client). Are you specifying a user and password that you have configured the server with for authentication as well?

**Comment by LORDlude** [comment]
@choppsv1 Yes,you are right.Neither in xshell nor VMware "ss anlp|grep 830" can acpture the netconfd listening on port 830. But why, I have add the port in the config file.When I run the server and client,The client can connect the server on localhost.The username and passwd is my VMware OS's (ubuntun14) username and passswd.I put a picture,can you see it ?
![image](https://user-images.githubusercontent.com/26692675/71862024-5ce7a700-3133-11ea-8a43-613bb6578506.png)

**Comment by LORDlude** [comment]
@choppsv1 Thanks for your help.Maybe a time difference between us. I am noob bird.(not  a  developer but only for interest).

**Comment by choppsv1** [comment]
To see the server process name you need to run "sudo ss -alnp". It will probably show your server in that case.

So can you try running the python client from inside the VM like you did with the yuma client, making sure to specify the same username and password values with it as well. You can also try specifying the host instead of letting it default to localhost too.

Thanks,
Chris.

**Comment by LORDlude** [comment]
@choppsv1 I found I made a low mistake,Iforget to connect the server before using netconf-client ... --hello. I use username and password ti connect the server,it broken an AuthenticationException.I am not sure whether my config file is right or not. I only modify the /etc/ssh/sshd_config.
![image](https://user-images.githubusercontent.com/26692675/72231206-1ee7f880-35f5-11ea-93f9-8ea6e84f99d1.png)

**Comment by LORDlude** [comment]
![AuthenticationException](https://user-images.githubusercontent.com/26692675/72231226-3f17b780-35f5-11ea-8d12-7830a1604c82.png)

**Comment by choppsv1** [comment]
It looks like you have 1 too many "=" signs in  your password argument.
